Repository pytroll/pyorbital, pull requests merged in 2021-12, with the labels that each got.

#82 Add historical TLE files link
  doc/source/index.rst
Labels: documentation

#89 Change tested Python versions to 3.8, 3.9 and 3.10
  .github/workflows/ci.yaml
Labels: enhancement

#92 Fix bogus designator assignment
  pyorbital/tests/test_tlefile.py
  pyorbital/tlefile.py
Labels: bug
