Repository pytroll/pyorbital, pull requests merged in 2024-11, with the labels that each got.

#146 Update CI to use Python 3.10 - 3.12 and plain Miniforge
  .github/workflows/ci.yaml
Labels: enhancement, PCW

#169 Switch to use pyproject.toml instead of setup.py, and skip versioneer
  .bandit
  .github/ISSUE_TEMPLATE.md
  .github/workflows/deploy-sdist.yaml
  .gitignore
  .pre-commit-config.yaml
  .stickler.yml
  CHANGELOG.md
  README.md
  changelog.rst
  continuous_integration/environment.yaml
  doc/source/conf.py
  doc/source/index.rst
  pyorbital/__init__.py
  pyorbital/astronomy.py
  pyorbital/check_platform.py
  pyorbital/fetch_tles.py
  pyorbital/geoloc.py
  pyorbital/geoloc_example.py
  pyorbital/geoloc_instrument_definitions.py
  pyorbital/logger.py
  pyorbital/orbital.py
  pyorbital/tests/SGP4-VER.TLE
  pyorbital/tests/test_aiaa.py
  pyorbital/tests/test_astronomy.py
  pyorbital/tests/test_geoloc.py
  pyorbital/tests/test_logging.py
  pyorbital/tests/test_orbital.py
  pyorbital/tests/test_tlefile.py
  pyorbital/tlefile.py
  pyorbital/version.py
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
Labels: enhancement, PCW

#118 Refactor and improve tests concerning the TLE file handling
  .github/PULL_REQUEST_TEMPLATE.md
  pyorbital/tests/test_tlefile.py
  pyorbital/tlefile.py
Labels: enhancement

#124 Implement SGDP4_NEAR_SIMP propagation
  pyorbital/orbital.py
Labels: enhancement

#171 Refactor _SGDB4 class
  pyorbital/orbital.py
Labels: enhancement

#170 Deprecate PPP_CONFIG_DIR for specifying config path
  pyorbital/tests/test_tlefile.py
  pyorbital/tlefile.py
  pyproject.toml
Labels: enhancement

#172 Update CI build action to work without setup.py
  .github/workflows/deploy-sdist.yaml
Labels: bug
